// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "tRex":return img`
........................
........................
..........ffffffffff....
.........ffffffffffff...
.........ff1fffffffff...
.........ffffffffffff...
.........ffffffffffff...
.........ffffffff.......
.........fffffffffff....
f.......fffffff.........
f......ffffffff.........
ff....fffffffffff.......
fff..ffffffffff.f.......
fffffffffffffff.........
fffffffffffffff.........
.fffffffffffff..........
..ffffffffffff..........
...ffffffffff...........
....ffffffff............
.....ffff.ff............
......ff...f............
......f....f............
......ff...ff...........
........................
`;
            case "image2":
            case "cactus":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . f f . . . . . . . 
. . f f . . f f f f . . . . . . 
. f f f f . f f f f . . . . . . 
. f f f f . f f f f . . . f . . 
. f f f f . f f f f . . f f f . 
. f f f f . f f f f . . f f f . 
. f f f f . f f f f . . f f f . 
. f f f f f f f f f . . f f f . 
. f f f f f f f f f . . f f f . 
. f f f f f f f f f . . f f f . 
. . f f f f f f f f . . f f f . 
. . . f f f f f f f f f f f . . 
. . . . f f f f f f f f f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . f f f f . . . . . . 
`;
            case "image3":
            case "fly":return img`
....ff..................
...fff..................
..fffff.................
.ffffff.................
ffffffffffffff..........
......fffffffff.........
.......fffffffffffffffff
........fffffffffff.....
........fffffffffffffff.
........ffffffffff......
........ffff............
........fff.............
........ff..............
........ff..............
........f...............
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
